from .agent_serializer import RequestAgentRegistrationSerializer, ResponseAgentRegistrationSerializer
from .landlord_serializer import RequestLandLordRegistrationSerializer, ResponseLandLordRegistrationSerializer
from .response_agent_serializer import ResponseAgentSerializer
from .request_avatar_serializer import RequestAvatarSerializer
from .response_landlord_serailizer import ResponseLandLordSerializer