name: Deploy to DigitalOcean

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy on DigitalOcean droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_HOST }} << EOF
            echo "Navigating to project directory"
            cd /root/projects/igs-backend

            echo "Cleaning working directory..."
            git reset --hard
            git clean -fd

            echo "Pulling latest changes..."
            git pull origin development

            echo "Stopping all containers..."
            docker compose down || true

            echo "Removing all containers..."
            docker rm -f \$(docker ps -aq) || true

            echo "Removing all images..."
            docker rmi -f \$(docker images -aq) || true

            echo "Removing all volumes..."
            docker volume rm \$(docker volume ls -q) || true

            echo "Pruning system (remove dangling images, containers, volumes)..."
            docker system prune -a --volumes -f || true

            echo "Building fresh containers..."
            docker compose build --no-cache || exit 1

            echo "Starting services..."
            docker compose up -d || exit 1

            echo "Container status:"
            docker compose ps

            echo "Deployment completed successfully"
          EOF
