name: Deploy to DigitalOcean

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy on DigitalOcean droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_HOST }} << EOF
            cd /root/projects/igs-backend

            echo "Pulling latest code from GitHub..."
            git reset --hard
            git clean -fd
            git pull origin development

            echo "Stopping containers and removing volumes..."
            docker compose down -v

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting containers..."
            docker compose up -d

            echo "Current container status:"
            docker compose ps

            echo "Deployment completed successfully"
          EOF
