name: Deploy to DigitalOcean

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo root contents
        run: ls -la

      - name: List igs_backend folder contents
        run: ls -la ./igs_backend

      - name: List kedesh_client folder contents
        run: ls -la ./kedesh_client

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy on DigitalOcean droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_HOST }} << 'EOF'
            set -e

            echo "Navigating to project directory"
            cd /root/projects/igs-backend 

            echo "Stopping running containers"
            docker compose down || true

            echo "Pulling latest code from GitHub"
            git pull origin development

            echo "Building images and starting containers"
            docker compose up --build -d

            echo "Deployment completed successfully"
          EOF
